# Generated by Django 3.0.8 on 2021-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBeats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='movie',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
